# Generated by Django 3.2.8 on 2021-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashok', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='date',
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
