# Generated by Django 3.2.8 on 2021-11-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashok', '0003_timeline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='full_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
