# Generated by Django 3.2.8 on 2021-11-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashok', '0004_projects_full_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ashok',
            new_name='Person',
        ),
    ]
